# Generated by Django 5.2.5 on 2025-08-09 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_country_district_media_neighborhood_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.IntegerField(choices=[(1, 'UZS'), (2, 'USD')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'On Moderation'), (3, 'Active'), (4, 'Deactivated by Moderator'), (5, 'Deactivated by Owner'), (6, 'Expired'), (7, 'Archived')], default=1)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not paid'), (1, 'Paid')], default=0)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('vip_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('top_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Apartment'), (2, 'House'), (3, 'Commercial'), (4, 'Land')], null=True)),
                ('purpose', models.IntegerField(blank=True, choices=[(1, 'Sale'), (2, 'Rent (Daily)'), (3, 'Rent (Long-term)')], null=True)),
                ('condition', models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Secondary')], null=True)),
                ('repair', models.IntegerField(blank=True, choices=[(0, 'No Need'), (1, 'Required'), (2, 'Good'), (3, 'Cosmetic'), (4, 'Euro'), (5, 'Design'), (6, 'Capital')], null=True)),
                ('quality', models.IntegerField(blank=True, choices=[(0, 'Not specified'), (1, 'Economy'), (2, 'Standard'), (3, 'Business'), (4, 'Lux')], null=True)),
                ('room_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floors_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.neighborhood')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region')),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
            },
        ),
    ]
