# Generated by Django 5.2.5 on 2025-08-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estate',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='estate.estateadvantage'),
        ),
        migrations.AddIndex(
            model_name='estate',
            index=models.Index(fields=['type', 'purpose'], name='estate_esta_type_5322cf_idx'),
        ),
    ]
